version: x.x.{build}
image: Visual Studio 2019
configuration: Release
before_build:
- cmd: appveyor-retry nuget restore
build:
  project: dnlib.sln
  parallel: true
  verbosity: normal
before_package:
- cmd: msbuild /m /p:Configuration=Release /t:Pack dnlib.sln
artifacts:
- path: src\bin\Release\*.*nupkg
  name: dnlib NuGet Packages
notifications:
- provider: Email
  to:
  - de4dot@gmail.com
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: false
deploy:
- provider: NuGet
  on:
    APPVEYOR_REPO_TAG: true
  api_key:
    secure: 1oWvNqv/17WGGwHiBAuPEXRbFUqG5ZIX83m51TNF1u/jIqAkjt8Ec4LI+jB9N5zh
